### PR TITLE
Revert "Clarify support for RootHide Dopamine only (pre Bootstrap sb)"

### PR DESCRIPTION
**Pull request by TweaksDev22**
Fix

### CODE REVIEW

**Comment by dleovl** [comment]
@TweaksDev22 Why? These tweaks are not compatible on the RootHide Bootstrap, only RootHide's fork of Dopamine.

**Comment by TweaksDev22** [comment]
@dleovl  these tweaks was testing only in roothide dopamine

**Comment by dleovl** [comment]
> @dleovl these tweaks was testing only in roothide dopamine

This repository doesn't explicitly state it was used for RootHide's fork of Dopamine. It should, considering how RootHide has also released a bootstrap that can inject tweaks. At least specify this isn't a list for RootHide Bootstrap.

**Comment by TweaksDev22** [comment]
@dleovl This has not been counted for a long time, and is not recognized by bootstrap, but you can add modifications to it and I have no objection to that.

**Comment by dleovl** [comment]
> @dleovl This has not been counted for a long time, and is not recognized by bootstrap, but you can add modifications to it and I have no objection to that.

You objected my modification.

**Comment by TweaksDev22** [comment]
> > @dleovl This has not been counted for a long time, and is not recognized by bootstrap, but you can add modifications to it and I have no objection to that.
> 
> You objected my modification.

Oh sorry maybe i hit  button by wrong , sorry about thats

**Comment by dleovl** [comment]
> > > @dleovl This has not been counted for a long time, and is not recognized by bootstrap, but you can add modifications to it and I have no objection to that.
> > 
> > 
> > You objected my modification.
> 
> Oh sorry maybe i hit button by wrong , sorry about thats

You still haven't reverted your revert PR.

**Pull request merged**
