### PR TITLE
Revert "Revert "Clarify support for RootHide Dopamine only (pre Bootstrap sb)""

### PR DESCRIPTION
**Pull request by TweaksDev22**
Reverts TweaksDev22/Tweakslist#4

### CODE REVIEW

**Comment by dleovl** [comment]
looks fine

**Comment by dleovl** [comment]
@TweaksDev22 Are you going to clarify it or not? People are linking to your repository assuming this is for the RootHide Bootstrap lmao

**Comment by TweaksDev22** [comment]
I will update it , but its already mentioned to roothide , not bootstrap ..

**Comment by dleovl** [comment]
> I will update it , but its already mentioned to roothide , not bootstrap ..

RootHide Dopamine and RootHide Bootstrap are two different things.

**Pull request closed without merging**
